name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
      - name: install ops
        run: |
          curl https://ops.city/get.sh -sSfL | sh
      - name: ops missing files
        run: |
          ops run --missing-files $HOME/.wasmtime/bin/wasmtime
      - name: ldd wasmtime
        run: |
          ls -la $HOME/.wasmtime
          ls -la $HOME/.wasmtime/bin
          ldd $(which $HOME/.wasmtime/bin/wasmtime)
